import type { VocabularyPartOfSpeech } from "./vocabulary.server";

export type A1VocabularyWordSeed = {
  en: string;
  kk: string;
  ru: string;
  emoji?: string;
};

export type A1VocabularyTopicSeed = {
  slug: string;
  title_en: string;
  title_kk: string;
  title_ru: string;
  description_en: string;
  description_kk: string;
  description_ru: string;
  icon: string;
  categories: Partial<Record<VocabularyPartOfSpeech, A1VocabularyWordSeed[]>>;
};

const w = (en: string, kk: string, ru: string, emoji?: string): A1VocabularyWordSeed => ({ en, kk, ru, emoji });

// Source: The Oxford 3000 by CEFR level (Oxford University Press), A1 tier.
// This is the first batch of A1 content rebuilt from that list; more A1
// topics (and A2/B1/B2) will follow in later updates.
export const a1VocabularyTopics: A1VocabularyTopicSeed[] = [
  {
    slug: "greetings-and-people",
    title_en: "Greetings & People",
    title_kk: "Амандасу және адамдар",
    title_ru: "Приветствия и люди",
    description_en: "First words for people and everyday greetings.",
    description_kk: "Адамдар мен күнделікті амандасуға керек алғашқы сөздер.",
    description_ru: "Первые слова о людях и повседневных приветствиях.",
    icon: "waving_hand",
    categories: {
      noun: [
        w("hello", "сәлем", "привет", "👋"),
        w("goodbye", "сау бол", "до свидания", "👋"),
        w("name", "есім", "имя", "📛"),
        w("friend", "дос", "друг", "🧑‍🤝‍🧑"),
        w("family", "отбасы", "семья", "👨‍👩‍👧‍👦"),
        w("mother", "ана", "мама", "👩"),
        w("father", "әке", "папа", "👨"),
        w("brother", "аға/іні", "брат", "👦"),
        w("sister", "апа/қарындас", "сестра", "👧"),
        w("boy", "бала (ұл)", "мальчик", "👦"),
        w("girl", "қыз", "девочка", "👧"),
        w("man", "ер адам", "мужчина", "👨"),
        w("woman", "әйел", "женщина", "👩"),
        w("baby", "нәресте", "малыш", "👶"),
        w("teacher", "мұғалім", "учитель", "👩‍🏫"),
      ],
    },
  },
  {
    slug: "time-and-calendar",
    title_en: "Time & Calendar",
    title_kk: "Уақыт және күнтізбе",
    title_ru: "Время и календарь",
    description_en: "Talk about days, dates and the time of day.",
    description_kk: "Күндер, мерзімдер және тәулік уақыты туралы сөйле.",
    description_ru: "Говорим о днях, датах и времени суток.",
    icon: "schedule",
    categories: {
      noun: [
        w("morning", "таң", "утро", "🌅"),
        w("afternoon", "түс", "день", "☀️"),
        w("evening", "кеш", "вечер", "🌆"),
        w("night", "түн", "ночь", "🌙"),
        w("day", "күн", "день", "📆"),
        w("week", "апта", "неделя", "📅"),
        w("month", "ай", "месяц", "🗓️"),
        w("year", "жыл", "год", "📆"),
        w("hour", "сағат", "час", "⏰"),
        w("minute", "минут", "минута", "⏱️"),
        w("time", "уақыт", "время", "⏳"),
        w("age", "жас", "возраст", "🎂"),
        w("date", "мерзім", "дата", "📅"),
        w("birthday", "туған күн", "день рождения", "🎂"),
        w("weekend", "демалыс күндері", "выходные", "🎉"),
      ],
    },
  },
  {
    slug: "home-and-rooms",
    title_en: "Home & Rooms",
    title_kk: "Үй және бөлмелер",
    title_ru: "Дом и комнаты",
    description_en: "Rooms and everyday objects at home.",
    description_kk: "Үйдегі бөлмелер мен күнделікті заттар.",
    description_ru: "Комнаты и повседневные предметы дома.",
    icon: "home",
    categories: {
      noun: [
        w("house", "үй", "дом", "🏠"),
        w("home", "үй-жай", "дом", "🏡"),
        w("room", "бөлме", "комната", "🚪"),
        w("bedroom", "жатын бөлме", "спальня", "🛏️"),
        w("bathroom", "жуынатын бөлме", "ванная", "🛁"),
        w("door", "есік", "дверь", "🚪"),
        w("window", "терезе", "окно", "🪟"),
        w("wall", "қабырға", "стена", "🧱"),
        w("table", "үстел", "стол", "🛋️"),
        w("chair", "орындық", "стул", "🪑"),
        w("bed", "төсек", "кровать", "🛏️"),
        w("clock", "қабырға сағаты", "часы", "🕐"),
        w("key", "кілт", "ключ", "🔑"),
        w("bag", "сөмке", "сумка", "👜"),
        w("box", "жәшік", "коробка", "📦"),
      ],
    },
  },
  {
    slug: "food-and-drink",
    title_en: "Food & Drink",
    title_kk: "Тағам және сусын",
    title_ru: "Еда и напитки",
    description_en: "Everyday meals, food and drinks.",
    description_kk: "Күнделікті тамақ, азық-түлік және сусындар.",
    description_ru: "Повседневная еда, продукты и напитки.",
    icon: "restaurant",
    categories: {
      noun: [
        w("breakfast", "таңғы ас", "завтрак", "🍳"),
        w("lunch", "түскі ас", "обед", "🍽️"),
        w("dinner", "кешкі ас", "ужин", "🍲"),
        w("food", "тағам", "еда", "🍱"),
        w("apple", "алма", "яблоко", "🍎"),
        w("banana", "банан", "банан", "🍌"),
        w("bread", "нан", "хлеб", "🍞"),
        w("cheese", "ірімшік", "сыр", "🧀"),
        w("chicken", "тауық", "курица", "🍗"),
        w("chocolate", "шоколад", "шоколад", "🍫"),
        w("coffee", "кофе", "кофе", "☕"),
        w("egg", "жұмыртқа", "яйцо", "🥚"),
        w("fish", "балық", "рыба", "🐟"),
        w("rice", "күріш", "рис", "🍚"),
        w("water", "су", "вода", "💧"),
      ],
    },
  },
  {
    slug: "body-and-health",
    title_en: "Body & Health",
    title_kk: "Дене және денсаулық",
    title_ru: "Тело и здоровье",
    description_en: "Parts of the body and basic health words.",
    description_kk: "Дене мүшелері және денсаулыққа қатысты негізгі сөздер.",
    description_ru: "Части тела и базовые слова о здоровье.",
    icon: "favorite",
    categories: {
      noun: [
        w("body", "дене", "тело", "🧍"),
        w("head", "бас", "голова", "🧠"),
        w("eye", "көз", "глаз", "👁️"),
        w("ear", "құлақ", "ухо", "👂"),
        w("arm", "қол (білек)", "рука", "💪"),
        w("hand", "алақан", "рука", "✋"),
        w("leg", "аяқ", "нога", "🦵"),
        w("hair", "шаш", "волосы", "💇"),
        w("face", "бет", "лицо", "😊"),
        w("mouth", "ауыз", "рот", "👄"),
        w("tooth", "тіс", "зуб", "🦷"),
        w("back", "арқа", "спина", "🧍"),
        w("foot", "табан", "стопа", "🦶"),
        w("doctor", "дәрігер", "врач", "🩺"),
        w("hospital", "аурухана", "больница", "🏥"),
      ],
    },
  },
  {
    slug: "school-and-learning",
    title_en: "School & Learning",
    title_kk: "Мектеп және білім",
    title_ru: "Школа и учёба",
    description_en: "Classroom words and school life.",
    description_kk: "Сынып сөздері және мектеп өмірі.",
    description_ru: "Слова о классе и школьной жизни.",
    icon: "school",
    categories: {
      noun: [
        w("school", "мектеп", "школа", "🏫"),
        w("class", "сынып", "класс", "📚"),
        w("classroom", "сынып бөлмесі", "классная комната", "🧑‍🏫"),
        w("book", "кітап", "книга", "📖"),
        w("pen", "қалам", "ручка", "🖊️"),
        w("pencil", "қарындаш", "карандаш", "✏️"),
        w("dictionary", "сөздік", "словарь", "📓"),
        w("homework", "үй тапсырмасы", "домашнее задание", "📝"),
        w("lesson", "сабақ", "урок", "📚"),
        w("exam", "емтихан", "экзамен", "📝"),
        w("question", "сұрақ", "вопрос", "❓"),
        w("answer", "жауап", "ответ", "✅"),
        w("word", "сөз", "слово", "🔤"),
        w("page", "бет", "страница", "📄"),
        w("story", "әңгіме", "история", "📖"),
      ],
    },
  },
  {
    slug: "nature-and-animals",
    title_en: "Nature & Animals",
    title_kk: "Табиғат және жануарлар",
    title_ru: "Природа и животные",
    description_en: "Weather, plants and common animals.",
    description_kk: "Ауа-райы, өсімдіктер және жиі кездесетін жануарлар.",
    description_ru: "Погода, растения и распространённые животные.",
    icon: "park",
    categories: {
      noun: [
        w("animal", "жануар", "животное", "🐾"),
        w("dog", "ит", "собака", "🐶"),
        w("cat", "мысық", "кошка", "🐱"),
        w("bird", "құс", "птица", "🐦"),
        w("horse", "жылқы", "лошадь", "🐴"),
        w("cow", "сиыр", "корова", "🐄"),
        w("tree", "ағаш", "дерево", "🌳"),
        w("flower", "гүл", "цветок", "🌸"),
        w("mountain", "тау", "гора", "⛰️"),
        w("river", "өзен", "река", "🏞️"),
        w("sea", "теңіз", "море", "🌊"),
        w("sun", "күн", "солнце", "☀️"),
        w("rain", "жаңбыр", "дождь", "🌧️"),
        w("snow", "қар", "снег", "❄️"),
        w("weather", "ауа-райы", "погода", "🌤️"),
      ],
    },
  },
  {
    slug: "common-verbs-1",
    title_en: "Common Verbs 1",
    title_kk: "Жиі етістіктер 1",
    title_ru: "Частые глаголы 1",
    description_en: "Everyday action words for beginners.",
    description_kk: "Бастауыштар үшін күнделікті іс-әрекет сөздері.",
    description_ru: "Повседневные слова-действия для начинающих.",
    icon: "directions_run",
    categories: {
      verb: [
        w("add", "қосу", "добавить", "➕"),
        w("agree", "келісу", "соглашаться", "🤝"),
        w("answer", "жауап беру", "отвечать", "✅"),
        w("arrive", "жету", "прибывать", "🛬"),
        w("ask", "сұрау", "спрашивать", "❓"),
        w("become", "болу", "становиться", "🔄"),
        w("begin", "бастау", "начинать", "▶️"),
        w("believe", "сену", "верить", "🙏"),
        w("bring", "алып келу", "приносить", "🎁"),
        w("build", "салу", "строить", "🏗️"),
        w("buy", "сатып алу", "покупать", "🛒"),
        w("call", "қоңырау шалу", "звонить", "📞"),
        w("change", "өзгерту", "менять", "🔁"),
        w("choose", "таңдау", "выбирать", "☑️"),
        w("climb", "өрмелеу", "залезать", "🧗"),
      ],
    },
  },
  {
    slug: "common-adjectives-1",
    title_en: "Common Adjectives 1",
    title_kk: "Жиі сын есімдер 1",
    title_ru: "Частые прилагательные 1",
    description_en: "Basic describing words for beginners.",
    description_kk: "Бастауыштар үшін негізгі сипаттау сөздері.",
    description_ru: "Базовые описательные слова для начинающих.",
    icon: "palette",
    categories: {
      adjective: [
        w("afraid", "қорыққан", "испуганный", "😨"),
        w("amazing", "ғажап", "потрясающий", "🤩"),
        w("angry", "ашулы", "злой", "😠"),
        w("bad", "жаман", "плохой", "👎"),
        w("beautiful", "әдемі", "красивый", "😍"),
        w("big", "үлкен", "большой", "🐘"),
        w("black", "қара", "чёрный", "⚫"),
        w("blue", "көк", "синий", "🔵"),
        w("bored", "көңілсіз", "скучающий", "😑"),
        w("boring", "қызықсыз", "скучный", "😴"),
        w("busy", "бос емес", "занятый", "🏃"),
        w("cheap", "арзан", "дешёвый", "💸"),
        w("clean", "таза", "чистый", "🧼"),
        w("cold", "суық", "холодный", "❄️"),
        w("common", "кең тараған", "обычный", "👥"),
      ],
    },
  },
  {
    slug: "numbers-1-to-1000",
    title_en: "Numbers",
    title_kk: "Сандар",
    title_ru: "Числа",
    description_en: "Count from one to a thousand.",
    description_kk: "Бірден мыңға дейін санау.",
    description_ru: "Считаем от одного до тысячи.",
    icon: "tag",
    categories: {
      number: [
        w("one", "бір", "один", "1️⃣"),
        w("two", "екі", "два", "2️⃣"),
        w("three", "үш", "три", "3️⃣"),
        w("four", "төрт", "четыре", "4️⃣"),
        w("five", "бес", "пять", "5️⃣"),
        w("six", "алты", "шесть", "6️⃣"),
        w("seven", "жеті", "семь", "7️⃣"),
        w("eight", "сегіз", "восемь", "8️⃣"),
        w("nine", "тоғыз", "девять", "9️⃣"),
        w("ten", "он", "десять", "🔟"),
        w("eleven", "он бір", "одиннадцать", "🔢"),
        w("twelve", "он екі", "двенадцать", "🔢"),
        w("twenty", "жиырма", "двадцать", "🔢"),
        w("hundred", "жүз", "сто", "💯"),
        w("thousand", "мың", "тысяча", "🔢"),
      ],
    },
  },
  {
    slug: "pronouns-and-determiners",
    title_en: "Pronouns & Determiners",
    title_kk: "Есімдіктер",
    title_ru: "Местоимения",
    description_en: "I, you, he, she, my, your — the words that stand in for people and things.",
    description_kk: "Мен, сен, ол, менің, сенің — адам мен затты алмастыратын сөздер.",
    description_ru: "Я, ты, он, она, мой, твой — слова, заменяющие людей и предметы.",
    icon: "people",
    categories: {
      pronoun: [
        w("I", "мен", "я", "🙋"),
        w("you", "сен/сіз", "ты/вы", "🫵"),
        w("he", "ол (ер)", "он", "👦"),
        w("she", "ол (әйел)", "она", "👧"),
        w("it", "ол (зат)", "оно", "📦"),
        w("we", "біз", "мы", "👨‍👩‍👧"),
        w("they", "олар", "они", "👥"),
        w("this", "бұл", "этот", "👉"),
        w("that", "сол/ол", "тот", "👈"),
        w("my", "менің", "мой", "🙋"),
        w("your", "сенің/сіздің", "твой/ваш", "🫵"),
        w("his", "оның (ер)", "его", "👦"),
        w("her", "оның (әйел)", "её", "👧"),
        w("our", "біздің", "наш", "👨‍👩‍👧"),
        w("their", "олардың", "их", "👥"),
      ],
    },
  },
];
