/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TopicChallengeRouteImport } from './routes/topic-challenge'
import { Route as SubjectsRouteImport } from './routes/subjects'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ProgressRouteImport } from './routes/progress'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PlanRouteImport } from './routes/plan'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as HomeRouteImport } from './routes/home'
import { Route as ExplainSolutionRouteImport } from './routes/explain-solution'
import { Route as ExamRouteImport } from './routes/exam'
import { Route as DiagnosticRouteImport } from './routes/diagnostic'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SubjectsSubjectIdRouteImport } from './routes/subjects.$subjectId'
import { Route as ApiWhatsappWeeklyReportRouteImport } from './routes/api/whatsapp-weekly-report'
import { Route as ApiTtsRouteImport } from './routes/api/tts'
import { Route as ApiReviewRouteImport } from './routes/api/review'
import { Route as ApiExplainSolutionRouteImport } from './routes/api/explain-solution'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as LessonSubjectIdTopicIdRouteImport } from './routes/lesson.$subjectId.$topicId'
import { Route as ApiTelegramWebhookRouteImport } from './routes/api/telegram/webhook'
import { Route as ApiTelegramSetupWebhookRouteImport } from './routes/api/telegram/setup-webhook'
import { Route as ApiParentSendTestMessageRouteImport } from './routes/api/parent/send-test-message'
import { Route as ApiParentCreateInviteRouteImport } from './routes/api/parent/create-invite'
import { Route as ApiCronSendWeeklyReportsRouteImport } from './routes/api/cron/send-weekly-reports'

const TopicChallengeRoute = TopicChallengeRouteImport.update({
  id: '/topic-challenge',
  path: '/topic-challenge',
  getParentRoute: () => rootRouteImport,
} as any)
const SubjectsRoute = SubjectsRouteImport.update({
  id: '/subjects',
  path: '/subjects',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressRoute = ProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanRoute = PlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const ExplainSolutionRoute = ExplainSolutionRouteImport.update({
  id: '/explain-solution',
  path: '/explain-solution',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamRoute = ExamRouteImport.update({
  id: '/exam',
  path: '/exam',
  getParentRoute: () => rootRouteImport,
} as any)
const DiagnosticRoute = DiagnosticRouteImport.update({
  id: '/diagnostic',
  path: '/diagnostic',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SubjectsSubjectIdRoute = SubjectsSubjectIdRouteImport.update({
  id: '/$subjectId',
  path: '/$subjectId',
  getParentRoute: () => SubjectsRoute,
} as any)
const ApiWhatsappWeeklyReportRoute = ApiWhatsappWeeklyReportRouteImport.update({
  id: '/api/whatsapp-weekly-report',
  path: '/api/whatsapp-weekly-report',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTtsRoute = ApiTtsRouteImport.update({
  id: '/api/tts',
  path: '/api/tts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReviewRoute = ApiReviewRouteImport.update({
  id: '/api/review',
  path: '/api/review',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiExplainSolutionRoute = ApiExplainSolutionRouteImport.update({
  id: '/api/explain-solution',
  path: '/api/explain-solution',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const LessonSubjectIdTopicIdRoute = LessonSubjectIdTopicIdRouteImport.update({
  id: '/lesson/$subjectId/$topicId',
  path: '/lesson/$subjectId/$topicId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTelegramWebhookRoute = ApiTelegramWebhookRouteImport.update({
  id: '/api/telegram/webhook',
  path: '/api/telegram/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTelegramSetupWebhookRoute = ApiTelegramSetupWebhookRouteImport.update({
  id: '/api/telegram/setup-webhook',
  path: '/api/telegram/setup-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiParentSendTestMessageRoute =
  ApiParentSendTestMessageRouteImport.update({
    id: '/api/parent/send-test-message',
    path: '/api/parent/send-test-message',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiParentCreateInviteRoute = ApiParentCreateInviteRouteImport.update({
  id: '/api/parent/create-invite',
  path: '/api/parent/create-invite',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronSendWeeklyReportsRoute =
  ApiCronSendWeeklyReportsRouteImport.update({
    id: '/api/cron/send-weekly-reports',
    path: '/api/cron/send-weekly-reports',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/careers': typeof CareersRoute
  '/diagnostic': typeof DiagnosticRoute
  '/exam': typeof ExamRoute
  '/explain-solution': typeof ExplainSolutionRoute
  '/home': typeof HomeRoute
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/plan': typeof PlanRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/progress': typeof ProgressRoute
  '/register': typeof RegisterRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/shop': typeof ShopRoute
  '/subjects': typeof SubjectsRouteWithChildren
  '/topic-challenge': typeof TopicChallengeRoute
  '/api/chat': typeof ApiChatRoute
  '/api/explain-solution': typeof ApiExplainSolutionRoute
  '/api/review': typeof ApiReviewRoute
  '/api/tts': typeof ApiTtsRoute
  '/api/whatsapp-weekly-report': typeof ApiWhatsappWeeklyReportRoute
  '/subjects/$subjectId': typeof SubjectsSubjectIdRoute
  '/api/cron/send-weekly-reports': typeof ApiCronSendWeeklyReportsRoute
  '/api/parent/create-invite': typeof ApiParentCreateInviteRoute
  '/api/parent/send-test-message': typeof ApiParentSendTestMessageRoute
  '/api/telegram/setup-webhook': typeof ApiTelegramSetupWebhookRoute
  '/api/telegram/webhook': typeof ApiTelegramWebhookRoute
  '/lesson/$subjectId/$topicId': typeof LessonSubjectIdTopicIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/careers': typeof CareersRoute
  '/diagnostic': typeof DiagnosticRoute
  '/exam': typeof ExamRoute
  '/explain-solution': typeof ExplainSolutionRoute
  '/home': typeof HomeRoute
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/plan': typeof PlanRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/progress': typeof ProgressRoute
  '/register': typeof RegisterRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/shop': typeof ShopRoute
  '/subjects': typeof SubjectsRouteWithChildren
  '/topic-challenge': typeof TopicChallengeRoute
  '/api/chat': typeof ApiChatRoute
  '/api/explain-solution': typeof ApiExplainSolutionRoute
  '/api/review': typeof ApiReviewRoute
  '/api/tts': typeof ApiTtsRoute
  '/api/whatsapp-weekly-report': typeof ApiWhatsappWeeklyReportRoute
  '/subjects/$subjectId': typeof SubjectsSubjectIdRoute
  '/api/cron/send-weekly-reports': typeof ApiCronSendWeeklyReportsRoute
  '/api/parent/create-invite': typeof ApiParentCreateInviteRoute
  '/api/parent/send-test-message': typeof ApiParentSendTestMessageRoute
  '/api/telegram/setup-webhook': typeof ApiTelegramSetupWebhookRoute
  '/api/telegram/webhook': typeof ApiTelegramWebhookRoute
  '/lesson/$subjectId/$topicId': typeof LessonSubjectIdTopicIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/careers': typeof CareersRoute
  '/diagnostic': typeof DiagnosticRoute
  '/exam': typeof ExamRoute
  '/explain-solution': typeof ExplainSolutionRoute
  '/home': typeof HomeRoute
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/plan': typeof PlanRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/progress': typeof ProgressRoute
  '/register': typeof RegisterRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/shop': typeof ShopRoute
  '/subjects': typeof SubjectsRouteWithChildren
  '/topic-challenge': typeof TopicChallengeRoute
  '/api/chat': typeof ApiChatRoute
  '/api/explain-solution': typeof ApiExplainSolutionRoute
  '/api/review': typeof ApiReviewRoute
  '/api/tts': typeof ApiTtsRoute
  '/api/whatsapp-weekly-report': typeof ApiWhatsappWeeklyReportRoute
  '/subjects/$subjectId': typeof SubjectsSubjectIdRoute
  '/api/cron/send-weekly-reports': typeof ApiCronSendWeeklyReportsRoute
  '/api/parent/create-invite': typeof ApiParentCreateInviteRoute
  '/api/parent/send-test-message': typeof ApiParentSendTestMessageRoute
  '/api/telegram/setup-webhook': typeof ApiTelegramSetupWebhookRoute
  '/api/telegram/webhook': typeof ApiTelegramWebhookRoute
  '/lesson/$subjectId/$topicId': typeof LessonSubjectIdTopicIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/careers'
    | '/diagnostic'
    | '/exam'
    | '/explain-solution'
    | '/home'
    | '/leaderboard'
    | '/login'
    | '/plan'
    | '/privacy'
    | '/profile'
    | '/progress'
    | '/register'
    | '/reports'
    | '/settings'
    | '/shop'
    | '/subjects'
    | '/topic-challenge'
    | '/api/chat'
    | '/api/explain-solution'
    | '/api/review'
    | '/api/tts'
    | '/api/whatsapp-weekly-report'
    | '/subjects/$subjectId'
    | '/api/cron/send-weekly-reports'
    | '/api/parent/create-invite'
    | '/api/parent/send-test-message'
    | '/api/telegram/setup-webhook'
    | '/api/telegram/webhook'
    | '/lesson/$subjectId/$topicId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/careers'
    | '/diagnostic'
    | '/exam'
    | '/explain-solution'
    | '/home'
    | '/leaderboard'
    | '/login'
    | '/plan'
    | '/privacy'
    | '/profile'
    | '/progress'
    | '/register'
    | '/reports'
    | '/settings'
    | '/shop'
    | '/subjects'
    | '/topic-challenge'
    | '/api/chat'
    | '/api/explain-solution'
    | '/api/review'
    | '/api/tts'
    | '/api/whatsapp-weekly-report'
    | '/subjects/$subjectId'
    | '/api/cron/send-weekly-reports'
    | '/api/parent/create-invite'
    | '/api/parent/send-test-message'
    | '/api/telegram/setup-webhook'
    | '/api/telegram/webhook'
    | '/lesson/$subjectId/$topicId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/careers'
    | '/diagnostic'
    | '/exam'
    | '/explain-solution'
    | '/home'
    | '/leaderboard'
    | '/login'
    | '/plan'
    | '/privacy'
    | '/profile'
    | '/progress'
    | '/register'
    | '/reports'
    | '/settings'
    | '/shop'
    | '/subjects'
    | '/topic-challenge'
    | '/api/chat'
    | '/api/explain-solution'
    | '/api/review'
    | '/api/tts'
    | '/api/whatsapp-weekly-report'
    | '/subjects/$subjectId'
    | '/api/cron/send-weekly-reports'
    | '/api/parent/create-invite'
    | '/api/parent/send-test-message'
    | '/api/telegram/setup-webhook'
    | '/api/telegram/webhook'
    | '/lesson/$subjectId/$topicId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CareersRoute: typeof CareersRoute
  DiagnosticRoute: typeof DiagnosticRoute
  ExamRoute: typeof ExamRoute
  ExplainSolutionRoute: typeof ExplainSolutionRoute
  HomeRoute: typeof HomeRoute
  LeaderboardRoute: typeof LeaderboardRoute
  LoginRoute: typeof LoginRoute
  PlanRoute: typeof PlanRoute
  PrivacyRoute: typeof PrivacyRoute
  ProfileRoute: typeof ProfileRoute
  ProgressRoute: typeof ProgressRoute
  RegisterRoute: typeof RegisterRoute
  ReportsRoute: typeof ReportsRoute
  SettingsRoute: typeof SettingsRoute
  ShopRoute: typeof ShopRoute
  SubjectsRoute: typeof SubjectsRouteWithChildren
  TopicChallengeRoute: typeof TopicChallengeRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiExplainSolutionRoute: typeof ApiExplainSolutionRoute
  ApiReviewRoute: typeof ApiReviewRoute
  ApiTtsRoute: typeof ApiTtsRoute
  ApiWhatsappWeeklyReportRoute: typeof ApiWhatsappWeeklyReportRoute
  ApiCronSendWeeklyReportsRoute: typeof ApiCronSendWeeklyReportsRoute
  ApiParentCreateInviteRoute: typeof ApiParentCreateInviteRoute
  ApiParentSendTestMessageRoute: typeof ApiParentSendTestMessageRoute
  ApiTelegramSetupWebhookRoute: typeof ApiTelegramSetupWebhookRoute
  ApiTelegramWebhookRoute: typeof ApiTelegramWebhookRoute
  LessonSubjectIdTopicIdRoute: typeof LessonSubjectIdTopicIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/topic-challenge': {
      id: '/topic-challenge'
      path: '/topic-challenge'
      fullPath: '/topic-challenge'
      preLoaderRoute: typeof TopicChallengeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subjects': {
      id: '/subjects'
      path: '/subjects'
      fullPath: '/subjects'
      preLoaderRoute: typeof SubjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progress': {
      id: '/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof ProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plan': {
      id: '/plan'
      path: '/plan'
      fullPath: '/plan'
      preLoaderRoute: typeof PlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explain-solution': {
      id: '/explain-solution'
      path: '/explain-solution'
      fullPath: '/explain-solution'
      preLoaderRoute: typeof ExplainSolutionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exam': {
      id: '/exam'
      path: '/exam'
      fullPath: '/exam'
      preLoaderRoute: typeof ExamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diagnostic': {
      id: '/diagnostic'
      path: '/diagnostic'
      fullPath: '/diagnostic'
      preLoaderRoute: typeof DiagnosticRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subjects/$subjectId': {
      id: '/subjects/$subjectId'
      path: '/$subjectId'
      fullPath: '/subjects/$subjectId'
      preLoaderRoute: typeof SubjectsSubjectIdRouteImport
      parentRoute: typeof SubjectsRoute
    }
    '/api/whatsapp-weekly-report': {
      id: '/api/whatsapp-weekly-report'
      path: '/api/whatsapp-weekly-report'
      fullPath: '/api/whatsapp-weekly-report'
      preLoaderRoute: typeof ApiWhatsappWeeklyReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tts': {
      id: '/api/tts'
      path: '/api/tts'
      fullPath: '/api/tts'
      preLoaderRoute: typeof ApiTtsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/review': {
      id: '/api/review'
      path: '/api/review'
      fullPath: '/api/review'
      preLoaderRoute: typeof ApiReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/explain-solution': {
      id: '/api/explain-solution'
      path: '/api/explain-solution'
      fullPath: '/api/explain-solution'
      preLoaderRoute: typeof ApiExplainSolutionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lesson/$subjectId/$topicId': {
      id: '/lesson/$subjectId/$topicId'
      path: '/lesson/$subjectId/$topicId'
      fullPath: '/lesson/$subjectId/$topicId'
      preLoaderRoute: typeof LessonSubjectIdTopicIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/telegram/webhook': {
      id: '/api/telegram/webhook'
      path: '/api/telegram/webhook'
      fullPath: '/api/telegram/webhook'
      preLoaderRoute: typeof ApiTelegramWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/telegram/setup-webhook': {
      id: '/api/telegram/setup-webhook'
      path: '/api/telegram/setup-webhook'
      fullPath: '/api/telegram/setup-webhook'
      preLoaderRoute: typeof ApiTelegramSetupWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/parent/send-test-message': {
      id: '/api/parent/send-test-message'
      path: '/api/parent/send-test-message'
      fullPath: '/api/parent/send-test-message'
      preLoaderRoute: typeof ApiParentSendTestMessageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/parent/create-invite': {
      id: '/api/parent/create-invite'
      path: '/api/parent/create-invite'
      fullPath: '/api/parent/create-invite'
      preLoaderRoute: typeof ApiParentCreateInviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/send-weekly-reports': {
      id: '/api/cron/send-weekly-reports'
      path: '/api/cron/send-weekly-reports'
      fullPath: '/api/cron/send-weekly-reports'
      preLoaderRoute: typeof ApiCronSendWeeklyReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface SubjectsRouteChildren {
  SubjectsSubjectIdRoute: typeof SubjectsSubjectIdRoute
}

const SubjectsRouteChildren: SubjectsRouteChildren = {
  SubjectsSubjectIdRoute: SubjectsSubjectIdRoute,
}

const SubjectsRouteWithChildren = SubjectsRoute._addFileChildren(
  SubjectsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CareersRoute: CareersRoute,
  DiagnosticRoute: DiagnosticRoute,
  ExamRoute: ExamRoute,
  ExplainSolutionRoute: ExplainSolutionRoute,
  HomeRoute: HomeRoute,
  LeaderboardRoute: LeaderboardRoute,
  LoginRoute: LoginRoute,
  PlanRoute: PlanRoute,
  PrivacyRoute: PrivacyRoute,
  ProfileRoute: ProfileRoute,
  ProgressRoute: ProgressRoute,
  RegisterRoute: RegisterRoute,
  ReportsRoute: ReportsRoute,
  SettingsRoute: SettingsRoute,
  ShopRoute: ShopRoute,
  SubjectsRoute: SubjectsRouteWithChildren,
  TopicChallengeRoute: TopicChallengeRoute,
  ApiChatRoute: ApiChatRoute,
  ApiExplainSolutionRoute: ApiExplainSolutionRoute,
  ApiReviewRoute: ApiReviewRoute,
  ApiTtsRoute: ApiTtsRoute,
  ApiWhatsappWeeklyReportRoute: ApiWhatsappWeeklyReportRoute,
  ApiCronSendWeeklyReportsRoute: ApiCronSendWeeklyReportsRoute,
  ApiParentCreateInviteRoute: ApiParentCreateInviteRoute,
  ApiParentSendTestMessageRoute: ApiParentSendTestMessageRoute,
  ApiTelegramSetupWebhookRoute: ApiTelegramSetupWebhookRoute,
  ApiTelegramWebhookRoute: ApiTelegramWebhookRoute,
  LessonSubjectIdTopicIdRoute: LessonSubjectIdTopicIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
