/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VocabularyRouteImport } from './routes/vocabulary'
import { Route as VerifyParentTelegramRouteImport } from './routes/verify-parent-telegram'
import { Route as TopicChallengeRouteImport } from './routes/topic-challenge'
import { Route as SubjectsRouteImport } from './routes/subjects'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ProgressRouteImport } from './routes/progress'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PlanRouteImport } from './routes/plan'
import { Route as PaymentRouteImport } from './routes/payment'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HomeRouteImport } from './routes/home'
import { Route as ExplainSolutionRouteImport } from './routes/explain-solution'
import { Route as ExamRouteImport } from './routes/exam'
import { Route as DiagnosticTestRouteImport } from './routes/diagnostic-test'
import { Route as DiagnosticResultRouteImport } from './routes/diagnostic-result'
import { Route as DiagnosticRouteImport } from './routes/diagnostic'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VocabularyWeakWordsRouteImport } from './routes/vocabulary.weak-words'
import { Route as VocabularyGamesRouteImport } from './routes/vocabulary.games'
import { Route as VocabularyTopicSlugRouteImport } from './routes/vocabulary.$topicSlug'
import { Route as SubjectsSubjectIdRouteImport } from './routes/subjects.$subjectId'
import { Route as ApiWhatsappWeeklyReportRouteImport } from './routes/api/whatsapp-weekly-report'
import { Route as ApiTtsRouteImport } from './routes/api/tts'
import { Route as ApiReviewRouteImport } from './routes/api/review'
import { Route as ApiExplainSolutionRouteImport } from './routes/api/explain-solution'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AdminVocabularyRouteImport } from './routes/admin.vocabulary'
import { Route as AdminPaymentsRouteImport } from './routes/admin.payments'
import { Route as VocabularyReviewPersonalizedRouteImport } from './routes/vocabulary.review.personalized'
import { Route as VocabularyTopicSlugFinalTestRouteImport } from './routes/vocabulary.$topicSlug.final-test'
import { Route as LessonSubjectIdTopicIdRouteImport } from './routes/lesson.$subjectId.$topicId'
import { Route as ApiTelegramWebhookInfoRouteImport } from './routes/api/telegram/webhook-info'
import { Route as ApiTelegramWebhookRouteImport } from './routes/api/telegram/webhook'
import { Route as ApiTelegramSetupWebhookRouteImport } from './routes/api/telegram/setup-webhook'
import { Route as ApiTelegramSetWebhookRouteImport } from './routes/api/telegram/set-webhook'
import { Route as ApiParentSendTestMessageRouteImport } from './routes/api/parent/send-test-message'
import { Route as ApiParentCreateInviteRouteImport } from './routes/api/parent/create-invite'
import { Route as ApiCronSendWeeklyReportsRouteImport } from './routes/api/cron/send-weekly-reports'
import { Route as ApiAiTutorChatRouteImport } from './routes/api/ai-tutor/chat'
import { Route as ApiAccountRegisterRouteImport } from './routes/api/account/register'
import { Route as VocabularyTopicSlugTestPartOfSpeechRouteImport } from './routes/vocabulary.$topicSlug.test.$partOfSpeech'

const VocabularyRoute = VocabularyRouteImport.update({
  id: '/vocabulary',
  path: '/vocabulary',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyParentTelegramRoute = VerifyParentTelegramRouteImport.update({
  id: '/verify-parent-telegram',
  path: '/verify-parent-telegram',
  getParentRoute: () => rootRouteImport,
} as any)
const TopicChallengeRoute = TopicChallengeRouteImport.update({
  id: '/topic-challenge',
  path: '/topic-challenge',
  getParentRoute: () => rootRouteImport,
} as any)
const SubjectsRoute = SubjectsRouteImport.update({
  id: '/subjects',
  path: '/subjects',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressRoute = ProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanRoute = PlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentRoute = PaymentRouteImport.update({
  id: '/payment',
  path: '/payment',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const ExplainSolutionRoute = ExplainSolutionRouteImport.update({
  id: '/explain-solution',
  path: '/explain-solution',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamRoute = ExamRouteImport.update({
  id: '/exam',
  path: '/exam',
  getParentRoute: () => rootRouteImport,
} as any)
const DiagnosticTestRoute = DiagnosticTestRouteImport.update({
  id: '/diagnostic-test',
  path: '/diagnostic-test',
  getParentRoute: () => rootRouteImport,
} as any)
const DiagnosticResultRoute = DiagnosticResultRouteImport.update({
  id: '/diagnostic-result',
  path: '/diagnostic-result',
  getParentRoute: () => rootRouteImport,
} as any)
const DiagnosticRoute = DiagnosticRouteImport.update({
  id: '/diagnostic',
  path: '/diagnostic',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VocabularyWeakWordsRoute = VocabularyWeakWordsRouteImport.update({
  id: '/weak-words',
  path: '/weak-words',
  getParentRoute: () => VocabularyRoute,
} as any)
const VocabularyGamesRoute = VocabularyGamesRouteImport.update({
  id: '/games',
  path: '/games',
  getParentRoute: () => VocabularyRoute,
} as any)
const VocabularyTopicSlugRoute = VocabularyTopicSlugRouteImport.update({
  id: '/$topicSlug',
  path: '/$topicSlug',
  getParentRoute: () => VocabularyRoute,
} as any)
const SubjectsSubjectIdRoute = SubjectsSubjectIdRouteImport.update({
  id: '/$subjectId',
  path: '/$subjectId',
  getParentRoute: () => SubjectsRoute,
} as any)
const ApiWhatsappWeeklyReportRoute = ApiWhatsappWeeklyReportRouteImport.update({
  id: '/api/whatsapp-weekly-report',
  path: '/api/whatsapp-weekly-report',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTtsRoute = ApiTtsRouteImport.update({
  id: '/api/tts',
  path: '/api/tts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReviewRoute = ApiReviewRouteImport.update({
  id: '/api/review',
  path: '/api/review',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiExplainSolutionRoute = ApiExplainSolutionRouteImport.update({
  id: '/api/explain-solution',
  path: '/api/explain-solution',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminVocabularyRoute = AdminVocabularyRouteImport.update({
  id: '/admin/vocabulary',
  path: '/admin/vocabulary',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPaymentsRoute = AdminPaymentsRouteImport.update({
  id: '/admin/payments',
  path: '/admin/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const VocabularyReviewPersonalizedRoute =
  VocabularyReviewPersonalizedRouteImport.update({
    id: '/review/personalized',
    path: '/review/personalized',
    getParentRoute: () => VocabularyRoute,
  } as any)
const VocabularyTopicSlugFinalTestRoute =
  VocabularyTopicSlugFinalTestRouteImport.update({
    id: '/final-test',
    path: '/final-test',
    getParentRoute: () => VocabularyTopicSlugRoute,
  } as any)
const LessonSubjectIdTopicIdRoute = LessonSubjectIdTopicIdRouteImport.update({
  id: '/lesson/$subjectId/$topicId',
  path: '/lesson/$subjectId/$topicId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTelegramWebhookInfoRoute = ApiTelegramWebhookInfoRouteImport.update({
  id: '/api/telegram/webhook-info',
  path: '/api/telegram/webhook-info',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTelegramWebhookRoute = ApiTelegramWebhookRouteImport.update({
  id: '/api/telegram/webhook',
  path: '/api/telegram/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTelegramSetupWebhookRoute = ApiTelegramSetupWebhookRouteImport.update({
  id: '/api/telegram/setup-webhook',
  path: '/api/telegram/setup-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTelegramSetWebhookRoute = ApiTelegramSetWebhookRouteImport.update({
  id: '/api/telegram/set-webhook',
  path: '/api/telegram/set-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiParentSendTestMessageRoute =
  ApiParentSendTestMessageRouteImport.update({
    id: '/api/parent/send-test-message',
    path: '/api/parent/send-test-message',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiParentCreateInviteRoute = ApiParentCreateInviteRouteImport.update({
  id: '/api/parent/create-invite',
  path: '/api/parent/create-invite',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronSendWeeklyReportsRoute =
  ApiCronSendWeeklyReportsRouteImport.update({
    id: '/api/cron/send-weekly-reports',
    path: '/api/cron/send-weekly-reports',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAiTutorChatRoute = ApiAiTutorChatRouteImport.update({
  id: '/api/ai-tutor/chat',
  path: '/api/ai-tutor/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAccountRegisterRoute = ApiAccountRegisterRouteImport.update({
  id: '/api/account/register',
  path: '/api/account/register',
  getParentRoute: () => rootRouteImport,
} as any)
const VocabularyTopicSlugTestPartOfSpeechRoute =
  VocabularyTopicSlugTestPartOfSpeechRouteImport.update({
    id: '/test/$partOfSpeech',
    path: '/test/$partOfSpeech',
    getParentRoute: () => VocabularyTopicSlugRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/careers': typeof CareersRoute
  '/dashboard': typeof DashboardRoute
  '/diagnostic': typeof DiagnosticRoute
  '/diagnostic-result': typeof DiagnosticResultRoute
  '/diagnostic-test': typeof DiagnosticTestRoute
  '/exam': typeof ExamRoute
  '/explain-solution': typeof ExplainSolutionRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/payment': typeof PaymentRoute
  '/plan': typeof PlanRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/progress': typeof ProgressRoute
  '/register': typeof RegisterRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/shop': typeof ShopRoute
  '/subjects': typeof SubjectsRouteWithChildren
  '/topic-challenge': typeof TopicChallengeRoute
  '/verify-parent-telegram': typeof VerifyParentTelegramRoute
  '/vocabulary': typeof VocabularyRouteWithChildren
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/vocabulary': typeof AdminVocabularyRoute
  '/api/chat': typeof ApiChatRoute
  '/api/explain-solution': typeof ApiExplainSolutionRoute
  '/api/review': typeof ApiReviewRoute
  '/api/tts': typeof ApiTtsRoute
  '/api/whatsapp-weekly-report': typeof ApiWhatsappWeeklyReportRoute
  '/subjects/$subjectId': typeof SubjectsSubjectIdRoute
  '/vocabulary/$topicSlug': typeof VocabularyTopicSlugRouteWithChildren
  '/vocabulary/games': typeof VocabularyGamesRoute
  '/vocabulary/weak-words': typeof VocabularyWeakWordsRoute
  '/api/account/register': typeof ApiAccountRegisterRoute
  '/api/ai-tutor/chat': typeof ApiAiTutorChatRoute
  '/api/cron/send-weekly-reports': typeof ApiCronSendWeeklyReportsRoute
  '/api/parent/create-invite': typeof ApiParentCreateInviteRoute
  '/api/parent/send-test-message': typeof ApiParentSendTestMessageRoute
  '/api/telegram/set-webhook': typeof ApiTelegramSetWebhookRoute
  '/api/telegram/setup-webhook': typeof ApiTelegramSetupWebhookRoute
  '/api/telegram/webhook': typeof ApiTelegramWebhookRoute
  '/api/telegram/webhook-info': typeof ApiTelegramWebhookInfoRoute
  '/lesson/$subjectId/$topicId': typeof LessonSubjectIdTopicIdRoute
  '/vocabulary/$topicSlug/final-test': typeof VocabularyTopicSlugFinalTestRoute
  '/vocabulary/review/personalized': typeof VocabularyReviewPersonalizedRoute
  '/vocabulary/$topicSlug/test/$partOfSpeech': typeof VocabularyTopicSlugTestPartOfSpeechRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/careers': typeof CareersRoute
  '/dashboard': typeof DashboardRoute
  '/diagnostic': typeof DiagnosticRoute
  '/diagnostic-result': typeof DiagnosticResultRoute
  '/diagnostic-test': typeof DiagnosticTestRoute
  '/exam': typeof ExamRoute
  '/explain-solution': typeof ExplainSolutionRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/payment': typeof PaymentRoute
  '/plan': typeof PlanRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/progress': typeof ProgressRoute
  '/register': typeof RegisterRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/shop': typeof ShopRoute
  '/subjects': typeof SubjectsRouteWithChildren
  '/topic-challenge': typeof TopicChallengeRoute
  '/verify-parent-telegram': typeof VerifyParentTelegramRoute
  '/vocabulary': typeof VocabularyRouteWithChildren
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/vocabulary': typeof AdminVocabularyRoute
  '/api/chat': typeof ApiChatRoute
  '/api/explain-solution': typeof ApiExplainSolutionRoute
  '/api/review': typeof ApiReviewRoute
  '/api/tts': typeof ApiTtsRoute
  '/api/whatsapp-weekly-report': typeof ApiWhatsappWeeklyReportRoute
  '/subjects/$subjectId': typeof SubjectsSubjectIdRoute
  '/vocabulary/$topicSlug': typeof VocabularyTopicSlugRouteWithChildren
  '/vocabulary/games': typeof VocabularyGamesRoute
  '/vocabulary/weak-words': typeof VocabularyWeakWordsRoute
  '/api/account/register': typeof ApiAccountRegisterRoute
  '/api/ai-tutor/chat': typeof ApiAiTutorChatRoute
  '/api/cron/send-weekly-reports': typeof ApiCronSendWeeklyReportsRoute
  '/api/parent/create-invite': typeof ApiParentCreateInviteRoute
  '/api/parent/send-test-message': typeof ApiParentSendTestMessageRoute
  '/api/telegram/set-webhook': typeof ApiTelegramSetWebhookRoute
  '/api/telegram/setup-webhook': typeof ApiTelegramSetupWebhookRoute
  '/api/telegram/webhook': typeof ApiTelegramWebhookRoute
  '/api/telegram/webhook-info': typeof ApiTelegramWebhookInfoRoute
  '/lesson/$subjectId/$topicId': typeof LessonSubjectIdTopicIdRoute
  '/vocabulary/$topicSlug/final-test': typeof VocabularyTopicSlugFinalTestRoute
  '/vocabulary/review/personalized': typeof VocabularyReviewPersonalizedRoute
  '/vocabulary/$topicSlug/test/$partOfSpeech': typeof VocabularyTopicSlugTestPartOfSpeechRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/careers': typeof CareersRoute
  '/dashboard': typeof DashboardRoute
  '/diagnostic': typeof DiagnosticRoute
  '/diagnostic-result': typeof DiagnosticResultRoute
  '/diagnostic-test': typeof DiagnosticTestRoute
  '/exam': typeof ExamRoute
  '/explain-solution': typeof ExplainSolutionRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/payment': typeof PaymentRoute
  '/plan': typeof PlanRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/progress': typeof ProgressRoute
  '/register': typeof RegisterRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/shop': typeof ShopRoute
  '/subjects': typeof SubjectsRouteWithChildren
  '/topic-challenge': typeof TopicChallengeRoute
  '/verify-parent-telegram': typeof VerifyParentTelegramRoute
  '/vocabulary': typeof VocabularyRouteWithChildren
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/vocabulary': typeof AdminVocabularyRoute
  '/api/chat': typeof ApiChatRoute
  '/api/explain-solution': typeof ApiExplainSolutionRoute
  '/api/review': typeof ApiReviewRoute
  '/api/tts': typeof ApiTtsRoute
  '/api/whatsapp-weekly-report': typeof ApiWhatsappWeeklyReportRoute
  '/subjects/$subjectId': typeof SubjectsSubjectIdRoute
  '/vocabulary/$topicSlug': typeof VocabularyTopicSlugRouteWithChildren
  '/vocabulary/games': typeof VocabularyGamesRoute
  '/vocabulary/weak-words': typeof VocabularyWeakWordsRoute
  '/api/account/register': typeof ApiAccountRegisterRoute
  '/api/ai-tutor/chat': typeof ApiAiTutorChatRoute
  '/api/cron/send-weekly-reports': typeof ApiCronSendWeeklyReportsRoute
  '/api/parent/create-invite': typeof ApiParentCreateInviteRoute
  '/api/parent/send-test-message': typeof ApiParentSendTestMessageRoute
  '/api/telegram/set-webhook': typeof ApiTelegramSetWebhookRoute
  '/api/telegram/setup-webhook': typeof ApiTelegramSetupWebhookRoute
  '/api/telegram/webhook': typeof ApiTelegramWebhookRoute
  '/api/telegram/webhook-info': typeof ApiTelegramWebhookInfoRoute
  '/lesson/$subjectId/$topicId': typeof LessonSubjectIdTopicIdRoute
  '/vocabulary/$topicSlug/final-test': typeof VocabularyTopicSlugFinalTestRoute
  '/vocabulary/review/personalized': typeof VocabularyReviewPersonalizedRoute
  '/vocabulary/$topicSlug/test/$partOfSpeech': typeof VocabularyTopicSlugTestPartOfSpeechRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/careers'
    | '/dashboard'
    | '/diagnostic'
    | '/diagnostic-result'
    | '/diagnostic-test'
    | '/exam'
    | '/explain-solution'
    | '/home'
    | '/login'
    | '/payment'
    | '/plan'
    | '/pricing'
    | '/privacy'
    | '/profile'
    | '/progress'
    | '/register'
    | '/reports'
    | '/settings'
    | '/shop'
    | '/subjects'
    | '/topic-challenge'
    | '/verify-parent-telegram'
    | '/vocabulary'
    | '/admin/payments'
    | '/admin/vocabulary'
    | '/api/chat'
    | '/api/explain-solution'
    | '/api/review'
    | '/api/tts'
    | '/api/whatsapp-weekly-report'
    | '/subjects/$subjectId'
    | '/vocabulary/$topicSlug'
    | '/vocabulary/games'
    | '/vocabulary/weak-words'
    | '/api/account/register'
    | '/api/ai-tutor/chat'
    | '/api/cron/send-weekly-reports'
    | '/api/parent/create-invite'
    | '/api/parent/send-test-message'
    | '/api/telegram/set-webhook'
    | '/api/telegram/setup-webhook'
    | '/api/telegram/webhook'
    | '/api/telegram/webhook-info'
    | '/lesson/$subjectId/$topicId'
    | '/vocabulary/$topicSlug/final-test'
    | '/vocabulary/review/personalized'
    | '/vocabulary/$topicSlug/test/$partOfSpeech'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/careers'
    | '/dashboard'
    | '/diagnostic'
    | '/diagnostic-result'
    | '/diagnostic-test'
    | '/exam'
    | '/explain-solution'
    | '/home'
    | '/login'
    | '/payment'
    | '/plan'
    | '/pricing'
    | '/privacy'
    | '/profile'
    | '/progress'
    | '/register'
    | '/reports'
    | '/settings'
    | '/shop'
    | '/subjects'
    | '/topic-challenge'
    | '/verify-parent-telegram'
    | '/vocabulary'
    | '/admin/payments'
    | '/admin/vocabulary'
    | '/api/chat'
    | '/api/explain-solution'
    | '/api/review'
    | '/api/tts'
    | '/api/whatsapp-weekly-report'
    | '/subjects/$subjectId'
    | '/vocabulary/$topicSlug'
    | '/vocabulary/games'
    | '/vocabulary/weak-words'
    | '/api/account/register'
    | '/api/ai-tutor/chat'
    | '/api/cron/send-weekly-reports'
    | '/api/parent/create-invite'
    | '/api/parent/send-test-message'
    | '/api/telegram/set-webhook'
    | '/api/telegram/setup-webhook'
    | '/api/telegram/webhook'
    | '/api/telegram/webhook-info'
    | '/lesson/$subjectId/$topicId'
    | '/vocabulary/$topicSlug/final-test'
    | '/vocabulary/review/personalized'
    | '/vocabulary/$topicSlug/test/$partOfSpeech'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/careers'
    | '/dashboard'
    | '/diagnostic'
    | '/diagnostic-result'
    | '/diagnostic-test'
    | '/exam'
    | '/explain-solution'
    | '/home'
    | '/login'
    | '/payment'
    | '/plan'
    | '/pricing'
    | '/privacy'
    | '/profile'
    | '/progress'
    | '/register'
    | '/reports'
    | '/settings'
    | '/shop'
    | '/subjects'
    | '/topic-challenge'
    | '/verify-parent-telegram'
    | '/vocabulary'
    | '/admin/payments'
    | '/admin/vocabulary'
    | '/api/chat'
    | '/api/explain-solution'
    | '/api/review'
    | '/api/tts'
    | '/api/whatsapp-weekly-report'
    | '/subjects/$subjectId'
    | '/vocabulary/$topicSlug'
    | '/vocabulary/games'
    | '/vocabulary/weak-words'
    | '/api/account/register'
    | '/api/ai-tutor/chat'
    | '/api/cron/send-weekly-reports'
    | '/api/parent/create-invite'
    | '/api/parent/send-test-message'
    | '/api/telegram/set-webhook'
    | '/api/telegram/setup-webhook'
    | '/api/telegram/webhook'
    | '/api/telegram/webhook-info'
    | '/lesson/$subjectId/$topicId'
    | '/vocabulary/$topicSlug/final-test'
    | '/vocabulary/review/personalized'
    | '/vocabulary/$topicSlug/test/$partOfSpeech'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CareersRoute: typeof CareersRoute
  DashboardRoute: typeof DashboardRoute
  DiagnosticRoute: typeof DiagnosticRoute
  DiagnosticResultRoute: typeof DiagnosticResultRoute
  DiagnosticTestRoute: typeof DiagnosticTestRoute
  ExamRoute: typeof ExamRoute
  ExplainSolutionRoute: typeof ExplainSolutionRoute
  HomeRoute: typeof HomeRoute
  LoginRoute: typeof LoginRoute
  PaymentRoute: typeof PaymentRoute
  PlanRoute: typeof PlanRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  ProfileRoute: typeof ProfileRoute
  ProgressRoute: typeof ProgressRoute
  RegisterRoute: typeof RegisterRoute
  ReportsRoute: typeof ReportsRoute
  SettingsRoute: typeof SettingsRoute
  ShopRoute: typeof ShopRoute
  SubjectsRoute: typeof SubjectsRouteWithChildren
  TopicChallengeRoute: typeof TopicChallengeRoute
  VerifyParentTelegramRoute: typeof VerifyParentTelegramRoute
  VocabularyRoute: typeof VocabularyRouteWithChildren
  AdminPaymentsRoute: typeof AdminPaymentsRoute
  AdminVocabularyRoute: typeof AdminVocabularyRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiExplainSolutionRoute: typeof ApiExplainSolutionRoute
  ApiReviewRoute: typeof ApiReviewRoute
  ApiTtsRoute: typeof ApiTtsRoute
  ApiWhatsappWeeklyReportRoute: typeof ApiWhatsappWeeklyReportRoute
  ApiAccountRegisterRoute: typeof ApiAccountRegisterRoute
  ApiAiTutorChatRoute: typeof ApiAiTutorChatRoute
  ApiCronSendWeeklyReportsRoute: typeof ApiCronSendWeeklyReportsRoute
  ApiParentCreateInviteRoute: typeof ApiParentCreateInviteRoute
  ApiParentSendTestMessageRoute: typeof ApiParentSendTestMessageRoute
  ApiTelegramSetWebhookRoute: typeof ApiTelegramSetWebhookRoute
  ApiTelegramSetupWebhookRoute: typeof ApiTelegramSetupWebhookRoute
  ApiTelegramWebhookRoute: typeof ApiTelegramWebhookRoute
  ApiTelegramWebhookInfoRoute: typeof ApiTelegramWebhookInfoRoute
  LessonSubjectIdTopicIdRoute: typeof LessonSubjectIdTopicIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vocabulary': {
      id: '/vocabulary'
      path: '/vocabulary'
      fullPath: '/vocabulary'
      preLoaderRoute: typeof VocabularyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-parent-telegram': {
      id: '/verify-parent-telegram'
      path: '/verify-parent-telegram'
      fullPath: '/verify-parent-telegram'
      preLoaderRoute: typeof VerifyParentTelegramRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/topic-challenge': {
      id: '/topic-challenge'
      path: '/topic-challenge'
      fullPath: '/topic-challenge'
      preLoaderRoute: typeof TopicChallengeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subjects': {
      id: '/subjects'
      path: '/subjects'
      fullPath: '/subjects'
      preLoaderRoute: typeof SubjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progress': {
      id: '/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof ProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plan': {
      id: '/plan'
      path: '/plan'
      fullPath: '/plan'
      preLoaderRoute: typeof PlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment': {
      id: '/payment'
      path: '/payment'
      fullPath: '/payment'
      preLoaderRoute: typeof PaymentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explain-solution': {
      id: '/explain-solution'
      path: '/explain-solution'
      fullPath: '/explain-solution'
      preLoaderRoute: typeof ExplainSolutionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exam': {
      id: '/exam'
      path: '/exam'
      fullPath: '/exam'
      preLoaderRoute: typeof ExamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diagnostic-test': {
      id: '/diagnostic-test'
      path: '/diagnostic-test'
      fullPath: '/diagnostic-test'
      preLoaderRoute: typeof DiagnosticTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diagnostic-result': {
      id: '/diagnostic-result'
      path: '/diagnostic-result'
      fullPath: '/diagnostic-result'
      preLoaderRoute: typeof DiagnosticResultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diagnostic': {
      id: '/diagnostic'
      path: '/diagnostic'
      fullPath: '/diagnostic'
      preLoaderRoute: typeof DiagnosticRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vocabulary/weak-words': {
      id: '/vocabulary/weak-words'
      path: '/weak-words'
      fullPath: '/vocabulary/weak-words'
      preLoaderRoute: typeof VocabularyWeakWordsRouteImport
      parentRoute: typeof VocabularyRoute
    }
    '/vocabulary/games': {
      id: '/vocabulary/games'
      path: '/games'
      fullPath: '/vocabulary/games'
      preLoaderRoute: typeof VocabularyGamesRouteImport
      parentRoute: typeof VocabularyRoute
    }
    '/vocabulary/$topicSlug': {
      id: '/vocabulary/$topicSlug'
      path: '/$topicSlug'
      fullPath: '/vocabulary/$topicSlug'
      preLoaderRoute: typeof VocabularyTopicSlugRouteImport
      parentRoute: typeof VocabularyRoute
    }
    '/subjects/$subjectId': {
      id: '/subjects/$subjectId'
      path: '/$subjectId'
      fullPath: '/subjects/$subjectId'
      preLoaderRoute: typeof SubjectsSubjectIdRouteImport
      parentRoute: typeof SubjectsRoute
    }
    '/api/whatsapp-weekly-report': {
      id: '/api/whatsapp-weekly-report'
      path: '/api/whatsapp-weekly-report'
      fullPath: '/api/whatsapp-weekly-report'
      preLoaderRoute: typeof ApiWhatsappWeeklyReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tts': {
      id: '/api/tts'
      path: '/api/tts'
      fullPath: '/api/tts'
      preLoaderRoute: typeof ApiTtsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/review': {
      id: '/api/review'
      path: '/api/review'
      fullPath: '/api/review'
      preLoaderRoute: typeof ApiReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/explain-solution': {
      id: '/api/explain-solution'
      path: '/api/explain-solution'
      fullPath: '/api/explain-solution'
      preLoaderRoute: typeof ApiExplainSolutionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/vocabulary': {
      id: '/admin/vocabulary'
      path: '/admin/vocabulary'
      fullPath: '/admin/vocabulary'
      preLoaderRoute: typeof AdminVocabularyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/payments': {
      id: '/admin/payments'
      path: '/admin/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AdminPaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vocabulary/review/personalized': {
      id: '/vocabulary/review/personalized'
      path: '/review/personalized'
      fullPath: '/vocabulary/review/personalized'
      preLoaderRoute: typeof VocabularyReviewPersonalizedRouteImport
      parentRoute: typeof VocabularyRoute
    }
    '/vocabulary/$topicSlug/final-test': {
      id: '/vocabulary/$topicSlug/final-test'
      path: '/final-test'
      fullPath: '/vocabulary/$topicSlug/final-test'
      preLoaderRoute: typeof VocabularyTopicSlugFinalTestRouteImport
      parentRoute: typeof VocabularyTopicSlugRoute
    }
    '/lesson/$subjectId/$topicId': {
      id: '/lesson/$subjectId/$topicId'
      path: '/lesson/$subjectId/$topicId'
      fullPath: '/lesson/$subjectId/$topicId'
      preLoaderRoute: typeof LessonSubjectIdTopicIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/telegram/webhook-info': {
      id: '/api/telegram/webhook-info'
      path: '/api/telegram/webhook-info'
      fullPath: '/api/telegram/webhook-info'
      preLoaderRoute: typeof ApiTelegramWebhookInfoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/telegram/webhook': {
      id: '/api/telegram/webhook'
      path: '/api/telegram/webhook'
      fullPath: '/api/telegram/webhook'
      preLoaderRoute: typeof ApiTelegramWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/telegram/setup-webhook': {
      id: '/api/telegram/setup-webhook'
      path: '/api/telegram/setup-webhook'
      fullPath: '/api/telegram/setup-webhook'
      preLoaderRoute: typeof ApiTelegramSetupWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/telegram/set-webhook': {
      id: '/api/telegram/set-webhook'
      path: '/api/telegram/set-webhook'
      fullPath: '/api/telegram/set-webhook'
      preLoaderRoute: typeof ApiTelegramSetWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/parent/send-test-message': {
      id: '/api/parent/send-test-message'
      path: '/api/parent/send-test-message'
      fullPath: '/api/parent/send-test-message'
      preLoaderRoute: typeof ApiParentSendTestMessageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/parent/create-invite': {
      id: '/api/parent/create-invite'
      path: '/api/parent/create-invite'
      fullPath: '/api/parent/create-invite'
      preLoaderRoute: typeof ApiParentCreateInviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/send-weekly-reports': {
      id: '/api/cron/send-weekly-reports'
      path: '/api/cron/send-weekly-reports'
      fullPath: '/api/cron/send-weekly-reports'
      preLoaderRoute: typeof ApiCronSendWeeklyReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai-tutor/chat': {
      id: '/api/ai-tutor/chat'
      path: '/api/ai-tutor/chat'
      fullPath: '/api/ai-tutor/chat'
      preLoaderRoute: typeof ApiAiTutorChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/account/register': {
      id: '/api/account/register'
      path: '/api/account/register'
      fullPath: '/api/account/register'
      preLoaderRoute: typeof ApiAccountRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vocabulary/$topicSlug/test/$partOfSpeech': {
      id: '/vocabulary/$topicSlug/test/$partOfSpeech'
      path: '/test/$partOfSpeech'
      fullPath: '/vocabulary/$topicSlug/test/$partOfSpeech'
      preLoaderRoute: typeof VocabularyTopicSlugTestPartOfSpeechRouteImport
      parentRoute: typeof VocabularyTopicSlugRoute
    }
  }
}

interface SubjectsRouteChildren {
  SubjectsSubjectIdRoute: typeof SubjectsSubjectIdRoute
}

const SubjectsRouteChildren: SubjectsRouteChildren = {
  SubjectsSubjectIdRoute: SubjectsSubjectIdRoute,
}

const SubjectsRouteWithChildren = SubjectsRoute._addFileChildren(
  SubjectsRouteChildren,
)

interface VocabularyTopicSlugRouteChildren {
  VocabularyTopicSlugFinalTestRoute: typeof VocabularyTopicSlugFinalTestRoute
  VocabularyTopicSlugTestPartOfSpeechRoute: typeof VocabularyTopicSlugTestPartOfSpeechRoute
}

const VocabularyTopicSlugRouteChildren: VocabularyTopicSlugRouteChildren = {
  VocabularyTopicSlugFinalTestRoute: VocabularyTopicSlugFinalTestRoute,
  VocabularyTopicSlugTestPartOfSpeechRoute:
    VocabularyTopicSlugTestPartOfSpeechRoute,
}

const VocabularyTopicSlugRouteWithChildren =
  VocabularyTopicSlugRoute._addFileChildren(VocabularyTopicSlugRouteChildren)

interface VocabularyRouteChildren {
  VocabularyTopicSlugRoute: typeof VocabularyTopicSlugRouteWithChildren
  VocabularyGamesRoute: typeof VocabularyGamesRoute
  VocabularyWeakWordsRoute: typeof VocabularyWeakWordsRoute
  VocabularyReviewPersonalizedRoute: typeof VocabularyReviewPersonalizedRoute
}

const VocabularyRouteChildren: VocabularyRouteChildren = {
  VocabularyTopicSlugRoute: VocabularyTopicSlugRouteWithChildren,
  VocabularyGamesRoute: VocabularyGamesRoute,
  VocabularyWeakWordsRoute: VocabularyWeakWordsRoute,
  VocabularyReviewPersonalizedRoute: VocabularyReviewPersonalizedRoute,
}

const VocabularyRouteWithChildren = VocabularyRoute._addFileChildren(
  VocabularyRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CareersRoute: CareersRoute,
  DashboardRoute: DashboardRoute,
  DiagnosticRoute: DiagnosticRoute,
  DiagnosticResultRoute: DiagnosticResultRoute,
  DiagnosticTestRoute: DiagnosticTestRoute,
  ExamRoute: ExamRoute,
  ExplainSolutionRoute: ExplainSolutionRoute,
  HomeRoute: HomeRoute,
  LoginRoute: LoginRoute,
  PaymentRoute: PaymentRoute,
  PlanRoute: PlanRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  ProfileRoute: ProfileRoute,
  ProgressRoute: ProgressRoute,
  RegisterRoute: RegisterRoute,
  ReportsRoute: ReportsRoute,
  SettingsRoute: SettingsRoute,
  ShopRoute: ShopRoute,
  SubjectsRoute: SubjectsRouteWithChildren,
  TopicChallengeRoute: TopicChallengeRoute,
  VerifyParentTelegramRoute: VerifyParentTelegramRoute,
  VocabularyRoute: VocabularyRouteWithChildren,
  AdminPaymentsRoute: AdminPaymentsRoute,
  AdminVocabularyRoute: AdminVocabularyRoute,
  ApiChatRoute: ApiChatRoute,
  ApiExplainSolutionRoute: ApiExplainSolutionRoute,
  ApiReviewRoute: ApiReviewRoute,
  ApiTtsRoute: ApiTtsRoute,
  ApiWhatsappWeeklyReportRoute: ApiWhatsappWeeklyReportRoute,
  ApiAccountRegisterRoute: ApiAccountRegisterRoute,
  ApiAiTutorChatRoute: ApiAiTutorChatRoute,
  ApiCronSendWeeklyReportsRoute: ApiCronSendWeeklyReportsRoute,
  ApiParentCreateInviteRoute: ApiParentCreateInviteRoute,
  ApiParentSendTestMessageRoute: ApiParentSendTestMessageRoute,
  ApiTelegramSetWebhookRoute: ApiTelegramSetWebhookRoute,
  ApiTelegramSetupWebhookRoute: ApiTelegramSetupWebhookRoute,
  ApiTelegramWebhookRoute: ApiTelegramWebhookRoute,
  ApiTelegramWebhookInfoRoute: ApiTelegramWebhookInfoRoute,
  LessonSubjectIdTopicIdRoute: LessonSubjectIdTopicIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
